baseURL = "https://thickdicknick.github.io/"
languageCode = "en"
title = "Thick Dick Nick"
theme = "hugo-initio"

[params]
    name = "The Thick Dick"
    description = "Colorado's most feared personal injury attorney"
    email = "nick@thickdicknick.com"
    phone = "1-800-THIK-DIK"
    address = "1 Thick Dick Way, Colorado Springs, CO"
    year = 2017
    avatar = "images/guy.jpg"
    avatarclass = "circle"
    background = ""
    banner = "images/bg_head.jpg"
    favicon = "images/gt_favicon.png"
    DateForm = "January 1, 2023"
    author = "Sergey Pozhilov (GetTemplate.com)"

    showSubheader = true
    showServices = true
    showRecentWorks = true
    showDownloads = true
    showClients = true

    showFooterContact = true
    showFooterFollowMe = true
    showFooterTextWidget = true
    showFooterFormWidget = true

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "blog"
    url = "/post/"
    weight = 5

[params.google.analytics]
    trackerID = "GA-000000000-0"

[[params.social]]
	title = "facebook"
	url = "https://www.facebook.com/thickdicknick"
    icon = "fab fa-facebook-square"
    footer = true
    sharethis = true
    network = "facebook"
[[params.social]]
	title = "twitter"
	url = "https://twitter.com/thickdicknick"
    icon = "fab fa-twitter-square"
    footer = true
    sharethis = true
    network = "twitter"
[[params.social]]
	title = "instagram"
	url = "https://www.instagram.com/thickdicknick"
    icon = "fab fa-instagram"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "google+"
	url = "https://plus.google.com/+thickdicknick"
    icon = "fab fa-google-plus-square"
    footer = false
    sharethis = true
    network = "googleplus"
[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/thickdicknick"
    icon = "fab fa-linkedin"
    footer = false
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "tumblr"
	url = "https://thickdicknick.tumblr.com"
    icon = "fab fa-tumblr-square"
    footer = false
    sharethis = false
    network = "tumblr"
[[params.social]]
	title = "email"
	url = "mailto:nick@thickdicknick.com"
    icon = "fas fa-envelope-square"
    footer = false
    sharethis = true
    network = "email"
